#!/usr/bin/python3
# coding=utf-8

Spanish_500Freq_Words = dict({'the--masculine': 'el', 'the--feminine; third-person feminine direct object pronoun': 'la', 'of, from': 'de', 'that, which': 'que', 'and': 'y', 
'to, at': 'a', 'in, on': 'en', 'a, an': 'un', 'to be (permanent)': 'ser', 'reflexive third-person pronoun': 'se', 
'no': 'no', 'to have (auxiliary)': 'haber', 'by, for, through': 'por', 'with': 'con', 'his, her, their, your': 'su', 'for, to, in order to': 'para', 'like, as': 'como', 'to be (temporary)': 'estar', 'to have (possess)': 'tener', 'third-person indirect object pronoun': 'le', 
'the, it (plus noun)': 'lo', 'all, every': 'todo', 'but, yet, except': 'pero', 'more': 'más', 'to do, make': 'hacer', 
'or': 'o', 'to be able to': 'poder', 'to tell, say': 'decir', 'this (masculine)': 'este', 'this (feminine)': 'esta', 'to go': 'ir', 
'other, another': 'otro', 'that (masculine)': 'ese', 'that (feminine)': 'esa', 'if, whether': 'si', 'me (object pronoun)': 'me', 'already, still': 'ya', 
'to see': 'ver', 'because': 'porque', 'to give': 'dar', 'when': 'cuando', 'he, him': 'él', 
'very, really': 'muy', 'without': 'sin', 'time (occasion)': 'vez', 'much, many, a lot': 'mucho(s)/mucha(s)', 'to know': 'saber', 
'what, which, how': 'qué', 'on top of, over, about': 'sobre', 'my': 'mi', 'some, someone': 'alguno(s)/alguna(s)', 'same': 'mismo', 
'I': 'yo', 'also': 'también', 'until, up to, even': 'hasta', 'year': 'año', 'two': 'dos', 
'to want, to love': 'querer', 'between, among': 'entre', 'like that': 'así', 'first': 'primero', 'from, since': 'desde', 
'large, great, big': 'grande', 'that': 'eso', 'not even, neither, nor': 'ni', 'us': 'nos', 'to arrive': 'llegar', 
'to pass': 'pasar', 'time, weather': 'tiempo', 'she, them': 'ella', 'yes': 'sí', 'day': 'día', 
'one': 'uno', 'well': 'bien', 'little, few, a little bit': 'poco(s)/poca(s)', 'should, ought to': 'deber', 'so, then': 'entonces',  
'to put': 'poner', 'thing': 'cosa', 'so much, so many': 'tanto(s), tanta(s)', 'man': 'hombre', 'to seem, to appear': 'parecer', 
'our': 'nuestro', 'such, as, too, so': 'tan', 'where': 'donde', 'now': 'ahora', 'part, portion': 'parte', 
'after': 'después', 'life': 'vida', 'to remain, to stay': 'quedar', 'always, forever': 'siempre', 'to believe': 'creer', 
'to speak': 'hablar', 'to take, to carry': 'llevar', 'to leave, to let': 'dejar', 'nothing': 'nada', 'each, every': 'cada', 
'to follow, to continue': 'seguir', 'less': 'menos', 'new': 'nuevo', 'to find': 'encontrar', 'something': 'algo', 
'only, just': 'sólo', 'then, well then': 'pues', 'to call': 'llamar', 'to come': 'venir', 'to think': 'pensar', 
'that (over there)': 'aquel', 'moment': 'momento', 'except, rather': 'sino', 'this': 'esto', 'to exit': 'salir', 
'to return, to come back': 'volver', 'form, shape, way': 'forma', 'before': 'antes', 'good': 'bueno', 'house': 'casa', 
'although, even though': 'aunque', 'world': 'mundo', 'three': 'tres', 'such': 'tal', 'better': 'mejor', 
'to take, to drink': 'tomar', 'certain, true': 'cierto', 'to get to know': 'conocer', 'toward': 'hacia', 'how': 'cómo', 
'woman': 'mujer', 'to live': 'vivir', 'here': 'aquí', 'case, situation': 'caso', 'to feel': 'sentir', 
'later, afterwards': 'luego', 'country': 'país', 'to treat, deal with, try': 'tratar', 'place': 'lugar', 'you--object pronoun': 'te', 
'person': 'persona', 'larger, older': 'mayor', 'last, final': 'último', 'own, proper': 'propio', 'who, whom': 'quien', 
'to look, watch': 'mirar', 'time, hour': 'hora', 'none, nobody': 'ningun(o)', 'work, job': 'trabajo', 'almost, nearly': 'casi', 
'point, dot, period': 'punto', 'during': 'durante', 'any, anyone': 'cualquier', 'hand': 'mano', 'never': 'nunca', 
'way, manner': 'manera', 'which, who, whom': 'cual', 'meanwhile, as long as': 'mientras', 'to count, tell a story': 'contar', 'end': 'fin', 
'type, kind': 'tipo', 'people': 'gente', 'besides, as well, further': 'además', 'lonely, alone': 'solo', 'to begin': 'empezar', 
'example': 'ejemplo', 'to wait, to hope': 'esperar', 'today': 'hoy', 'side': 'lado', 'son': 'hijo', 
'over there': 'allí', 'this one': 'éste', 'problem': 'problema', 'the bill, account': 'cuenta', 'middle, half, mean': 'medio', 
'against, opposite': 'contra', 'to look for': 'buscar', 'inside': 'dentro', 'long': 'largo', 'word': 'palabra', 
'to exist': 'existir', 'child': 'niño', 'to enter': 'entrar', 'nevertheless': 'embargo', 'only, unique, sole': 'único', 
'father': 'padre', 'to work': 'trabajar', 'small, little': 'pequeño', 'tall, high': 'alto', 'change': 'cambio',
'to write': 'escribir', 'four': 'cuatro', 'there': 'ahí', 'to lose': 'perder', 'we': 'nosotros', 
'story, history': 'historia', 'idea': 'idea', 'water': 'agua', 'to produce': 'producir', 'night': 'noche', 
'city': 'ciudad', 'way, manner': 'modo', 'name': 'nombre', 'to happen, occur': 'ocurrir', 'family': 'familia', 
'reality, actuality': 'realidad', 'to understand': 'entender', 'to ask for': 'pedir', 'to receive': 'recibir', 'work, deed, creation': 'obra', 
'important': 'importante', 'truth': 'verdad', 'month': 'mes', 'still, yet': 'todavía', 'reason': 'razón', 
'in terms of, regarding': 'en cuanto a', 'under, underneath': 'bajo', 'to remember, remind': 'recordar', 'group': 'grupo', 'a thousand': 'mil', 
'human': 'humano', 'to finish, end': 'terminar', 'to allow, permit': 'permitir', 'to appear': 'aparecer', 'to acquire, obtain': 'conseguir', 
'to begin, commence': 'comenzar', 'several, various': 'varios', 'possible': 'posible', 'to serve': 'servir', 'general': 'general', 
'to take out': 'sacar', 'to need': 'necesitar', 'relationship, relation': 'relación', 'five': 'cinco', 'body': 'cuerpo', 
'nobody': 'nadie', 'to maintain, keep': 'mantener', 'fact': 'hecho', 'in the presence of, before': 'ante', 'beginning, principle': 'principio', 
'to result, to turn out': 'resultar', 'equal, same as': 'igual', 'sir, Mr.': 'señor', 'people, village': 'pueblo', 'afternoon': 'tarde', 
'second': 'segundo', 'to read': 'leer', 'to fall': 'caer', 'to change': 'cambiar', 'eye': 'ojo', 
'street': 'calle', 'to present, introduce': 'presentar', 'white': 'blanco', 'to create': 'crear', 'to open': 'abrir', 
'book': 'libro', 'distinct, different': 'distinto', 'force, strength': 'fuerza', 'light': 'luz', 'according to': 'según', 
'saint': 'santo', 'clear': 'claro', 'in front of, facing': 'frente', 'to consider': 'considerar', 'friend': 'amigo', 
'to hear': 'oír', 'whose': 'cuyo', 'sense, feeling': 'sentido', 'to have just, to have finished': 'acabar', 'step': 'paso', 
'situation': 'situación', 'you': 'usted', 'enough, rather, quite a bit': 'bastante', 'to convert, become, change': 'convertir', 'thank you, grace': 'gracias', 
'century, age': 'siglo', 'god': 'dios', 'bad': 'malo', 'earth, land': 'tierra', 'paper': 'papel',  
'mother': 'madre', 'neither, nor, either': 'tampoco', 'social': 'social', 'old': 'viejo', 'still, yet': 'aún', 
'theme, subject, topic': 'tema', 'political': 'político', 'Spanish': 'español', 'to win, to earn': 'ganar', 'to form': 'formar', 
'kind, class, order': 'clase', 'to bring': 'traer', 'to divide, leave, starting from': 'partir', 'money': 'dinero', 'who, whom': 'quién', 
'to die': 'morir', 'including': 'incluso', 'field, country': 'campo', 'to accept': 'aceptar', 'perhaps, maybe': 'quizás', 
'head': 'cabeza', 'to fulfill, carry out': 'realizar', 'hundred': 'ciento', 'badly': 'mal', 'order, sequence': 'orden', 
'Mr.': 'don', 'week': 'semana', 'to suppose, assume': 'suponer', 'to understand': 'comprender', 'in the end, finally': 'al final', 
'interest': 'interés', 'next, following': 'siguiente', 'view': 'vista', 'to achieve, get, manage': 'lograr', 'the rest, the others': 'los/las demás', 
'accord, agreement': 'acuerdo', 'difficult': 'difícil', 'number': 'número', 'to explain': 'explicar', 'black': 'negro', 
'bottom, depth': 'fondo', 'road, way': 'camino', 'voice': 'voz', 'study, learning': 'estudio', 'necessary': 'necesario', 
'to ask': 'preguntar', 'over there': 'allá', 'to touch, to play (instrument)': 'tocar', 'value': 'valor', 'to recognize, admit': 'reconocer', 
'to study': 'estudiar', 'to reach': 'alcanzar', 'to be born': 'nacer', 'to direct': 'dirigir', 'to run': 'correr', 
'to measure': 'medida', 'younger': 'menor', 'too much': 'demasiado', 'only': 'solamente', 'to use, utilize': 'utilizar', 
'center, middle': 'centro', 'necessity': 'necesidad', 'condition': 'condición', 'to pay': 'pagar', 'it': 'ello', 
'lack, shortage': 'falta', 'to help': 'ayudar', 'ten': 'diez', 'across, over, through': 'través', 'old, ancient, former': 'antiguo', 
'your': 'tu', 'age': 'edad', 'state': 'estado, condition, status', 'to please': 'gustar', 'door': 'puerta', 
'to play': 'jugar', 'face': 'cara', 'me (object preposition)': 'mí', 'period, epoch': 'época', 'color': 'color', 
'to listen': 'escuchar', 'experience': 'experiencia', 'movement': 'movimiento', 'to fulfill': 'cumplir', 'special': 'especial', 
'different': 'diferente', 'to weigh': 'pesar', 'possibility': 'posibilidad', 'to offer': 'ofrecer', 'to discover': 'descubrir', 
'previous, preceding': 'anterior', 'game': 'juego', 'to rise up, lift': 'levantar', 'poor': 'pobre', 'air': 'aire', 
'six': 'seis', 'to try, attempt': 'intentar', 'war': 'guerra', 'together with, next to': 'junto', 'result, outcome': 'resultado', 
'to use': 'usar', 'to decide': 'decidir', 'to repeat': 'repetir', 'to forget': 'olvidar', 'law, rule': 'ley', 
'aspect, appearance': 'aspecto', 'foot, base': 'pie', 'to be worth, cost': 'valer', 'kind, species': 'especie', 'to eat': 'comer', 
'service': 'servicio', 'close, near': 'cerca', 'to show': 'mostrar', 'activity': 'actividad', 'third': 'tercero/tercera', 
'which': 'cuál', 'soon, quick': 'pronto', 'to occupy, use': 'ocupar', 'question, matter': 'cuestión', 'doubt': 'duda', 
'difference': 'diferencia', 'tomorrow, morning': 'mañana', 'to move, incite': 'mover', 'to continue': 'continuar', 'quantity, amount': 'cantidad',  
'action': 'acción', 'to happen': 'suceder', 'to fix, set': 'fijar', 'society': 'sociedad', 'to refer to': 'referir', 
'to come near': 'acercar', 'capable, able': 'capaz', 'free': 'libre',  'natural': 'natural', 'to dedicate, devote': 'dedicar', 
'really, actually, in fact': 'realmente', 'weight, load, peso': 'peso', 'effect': 'efecto', 'object': 'objeto', 'true, real': 'verdadero', 
'where': 'dónde', 'to learn': 'aprender', 'love': 'amor', 'death': 'muerte', 'party, group, match': 'partido', 
'economic': 'económico', 'right, justice, law': 'derecho', 'power': 'poder', 'importance': 'importancia', 'system': 'sistema', 
'travel, trip': 'viaje', 'ground, floor': 'suelo', 'respect': 'respecto', 'knowledge': 'conocimiento', 'liberty, freedom': 'libertad', 
'above, on top, in addition': 'encima', 'to buy': 'comprar', 'common': 'común', 'open': 'abierto', 'next': 'próximo', 
'attention': 'atención', 'young': 'joven', 'to go up': 'subir', 'effort, endeavor': 'esfuerzo', 'past, last': 'pasado', 
'to avoid': 'evitar', 'rest, remainder': 'resto', 'to interest': 'interesar', 'area, zone': 'zona', 'fear': 'miedo', 
'out, outside, away': 'fuera', 'process, procedure': 'proceso', 'alive': 'vivo', 'to close': 'cerrar', 'to throw, cast': 'echar', 
'to respond, answer': 'responder', 'to suffer, undergo': 'sufrir', 'complete': 'completo', 'minute': 'minuto', 'contrary, opposite': 'contrario', 
'table': 'mesa', 'real, royal, authentic': 'real', 'ocassion': 'ocasión', 'to matter': 'importar', 'public': 'público', 
'to obtain': 'obtener', 'program, plan': 'programa', 'favor, benefit': 'favor', 'far': 'lejos', 'seven': 'siete', 
'enormous, vast': 'enorme', 'answer, reply': 'respuesta', 'line, course': 'línea', 'space': 'espacio', 'level': 'nivel', 
'government': 'gobierno', 'end, bit': 'cabo', 'to observe': 'observar', 'to indicate': 'indicar', 'somebody, someone': 'alguien', 
'question': 'pregunta', 'back, behind, ago': 'atrás', 'image': 'imagen', 'career. course, race': 'carrera', 'to imagine': 'imaginar', 
'to become accustomed to': 'soler', 'both': 'ambos', 'deep, profound': 'profundo', 'to stop, detain': 'detener', 'to develop, unroll': 'desarrollar', 
'eight': 'ocho', 'to signal, point out': 'señalar', 'to choose, elect': 'elegir', 'figure': 'figura', 'main, principal': 'principal', 
'animal': 'animal', 'base, basis': 'base', 'to prepare': 'preparar', 'to propose': 'proponer', 'to demonstrate': 'demostrar', 
'to mean': 'significar', 'position': 'posición', 'motive': 'motivo', 'proof, test': 'prueba', 'politics, policy': 'política'
 })